server:
  port: 8080

spring:
  application:
    name: car-info
  batch:
    job:
      enabled: false
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

home.dir: "C:/car-info/storage"